services:
  geoweb:
    image: opengeoweb/geoweb
    container_name: geoweb
    restart: unless-stopped
    environment:
      - GW_APP_URL=https://geoweb.${APPDOMAIN:-local}
      - GW_AUTH_TOKEN_URL=${GW_AUTH_TOKEN_URL:-https://oauth2.googleapis.com/token}
      - GW_AUTH_LOGIN_URL=${GW_AUTH_LOGIN_URL:-https://accounts.google.com/o/oauth2/v2/auth}
      - GW_AUTH_LOGOUT_URL=${GW_AUTH_LOGOUT_URL:-}
      - GW_AUTH_CLIENT_ID=${GW_AUTH_CLIENT_ID:-}
      - GW_DEFAULT_THEME=lightTheme
      - GW_FEATURE_APP_TITLE=${GW_FEATURE_APP_TITLE:-GeoWeb}
      - GW_INITIAL_PRESETS_FILENAME=custom/initialPresets.json
    labels:
      - "traefik.http.routers.geoweb.entrypoints=websecure"
      - "traefik.http.routers.geoweb.rule=Host(`geoweb.${APPDOMAIN:-local}`)"
      - "traefik.http.services.geoweb.loadbalancer.server.port=8080"
    volumes:
      - /smartmet/cnf/geoweb:/usr/share/nginx/html/assets/custom
    networks:
      - traefik-network
  
networks:
    traefik-network:
      external: true
